data: 
  module: datasets.qm9
  root: data
  raw: data/raw
  batch_size: 32

trainer: 
  seed : 1111
  checkpoint_dir: trained_models
  vqvae_checkpoint: vqvae.ckpt
  checkpoint_interval: 20
  log_dir: logs
  precision: 16-mixed
  accelerator: cuda
  epochs : 500
  lr: 0.0001

transform: 
  resolution: 64
  num_thetas: 64
  structured_directions: True
  ambient_dimension: 3
  max_channels: 3
  scale: 200
  r: 1


vae:
  z_channels: 9
  codebook_size : 1024
  down_channels : [64,  128, 256, 256]
  mid_channels : [256, 256]
  down_sample : [True, False, False]
  attn_down : [False, False,False]
  norm_channels: 32
  im_channels : 3
  num_heads: 4
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2

discriminator:
  im_channels: 3

train:
  disc_start: 1000
  disc_weight: 0.5
  codebook_weight: 1
  commitment_beta: 0.2
  perceptual_weight: 1
  kl_weight: 0.000005
  save_latents : False
